---
# see https://pre-commit.com

exclude: ^package.*.json$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.15
    hooks:
      - id: actionlint-docker

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.3.1
    hooks:
      - id: cspell

  # see: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_fmt

  # textlint
  - repo: local
    hooks:
      - id: textlint
        name: textlint
        language: node
        types: [file]
        files: \.(md)$
        entry: textlint
        require_serial: false
        additional_dependencies:
          - "textlint@12.2.1"
          - "textlint-filter-rule-allowlist@4.0.0"
          - "textlint-rule-ja-no-space-between-full-width@2.2.0"
          - "textlint-filter-rule-comments@1.2.2"
          - "textlint-rule-no-dropping-the-ra@3.0.0"
          - "textlint-rule-terminology@3.0.1"
