---
name: Terraform - AWS - Sandbox

on:
  pull_request:
    paths:
      - ".github/actions/**/action.yml"
      - ".github/workflows/terraform-aws-sandbox.yml"
      - ".terraform-version"
      - "terraform/environments/sandbox/**"
      - "terraform/modules/**"
      - "terraform/usecases/**"
  push:
    branches:
      - main
    paths:
      - ".github/actions/**/action.yml"
      - ".github/workflows/terraform-aws-sandbox.yml"
      - ".terraform-version"
      - "terraform/environments/sandbox/**"
      - "terraform/modules/**"
      - "terraform/usecases/**"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  id-token: write
  pull-requests: write

concurrency: terraform-aws-sandbox

env:
  AWS_ACCOUNT_ID: 107662415716
  AWS_ENV_NAME: sandbox
  OIDC_IAM_ROLE: sandbox-terraform-aws-deploy

jobs:
  set-matrix:
    name: Set Matrix
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set Matrix
        id: set-matrix
        uses: ./.github/actions/set-matrix
        with:
          AWS_ENV_NAME: ${{ env.AWS_ENV_NAME }}

  terraform:
    name: Terraform
    needs: [set-matrix]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.set-matrix.outputs.matrix )}}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: AWS Credential
        uses: ./.github/actions/aws-credential
        with:
          oidc-iam-role: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.OIDC_IAM_ROLE }}

      - name: Terraform Plan
        uses: ./.github/actions/terraform-plan
        with:
          env_name: ${{ env.AWS_ENV_NAME }}
          working-directory: ./terraform/environments/${{ env.AWS_ENV_NAME }}/${{ matrix.directory }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Deployment
        if: github.ref == 'refs/heads/main'
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.AWS_ENV_NAME }}

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: ./.github/actions/terraform-apply
        with:
          working-directory: ./terraform/environments/${{ env.AWS_ENV_NAME }}/${{ matrix.directory }}

      - name: Finish Deployment
        if: always() && github.ref == 'refs/heads/main'
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
